---
abstract: 'Main Module CellBIS Toolkit based on Mojolicious'
author:
  - 'Achmad Yusri Afandi <yusrideb@cpan.org>'
build_requires:
  Module::Build: '0.3601'
configure_requires:
  ExtUtils::MakeMaker: '0'
  File::ShareDir::Install: '0.06'
  Module::Build: '0.3601'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.010, CPAN::Meta::Converter version 2.150010'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: CellBIS
requires:
  Carp: '0'
  Config::INI::Reader: '0'
  Config::INI::Writer: '0'
  Crypt::JWT: '0'
  Cwd: '0'
  DBI: '0'
  DBIx::Connector: '0'
  Data::Dumper: '0'
  DateTime: '0'
  Digest::MD5: '0'
  Exporter: '0'
  File::Basename: '0'
  File::ShareDir: '0'
  File::Spec: '0'
  File::Spec::Functions: '0'
  Getopt::Long: '0'
  Hash::Merge: '0'
  Hash::MultiValue: '0'
  JSON::XS: '0'
  List::SomeUtils: '0'
  List::Util: '0'
  Log::Log4perl: '0'
  MIME::Base64: '0'
  Mojo::Asset::File: '0'
  Mojo::Base: '0'
  Mojo::ByteStream: '0'
  Mojo::Cookie::Response: '0'
  Mojo::DOM: '0'
  Mojo::File: '0'
  Mojo::JSON: '0'
  Mojo::Loader: '0'
  Mojo::URL: '0'
  Mojo::Util: '0'
  Mojolicious: '0'
  Pod::Simple::Search: '0'
  Pod::Simple::XHTML: '0'
  Scalar::Util: '0'
  String::Random: '0'
  String::Util: '0'
  UI::Dialog: '0'
  UI::Dialog::Backend::CDialog: '0'
  UI::Dialog::Backend::Whiptail: '0'
  base: '0'
  strict: '0'
  vars: '0'
  warnings: '0'
version: '0.1'
x_serialization_backend: 'YAML::Tiny version 1.70'
